title: Congress 2018
description: >-
  A short description
long_description: >-
  A long description which goes on and on and on and on and on and on and on
  and on and on and on and on and on and on and on and on and on and on and on
  and on and on and on and on and on and on and on and on and on and on ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  talks:
    output: true
    permalink: /:collection/:title
  speakers:
    output: true
    permalink: /:collection/:title
  location:
    output: true
    permalink: /:collection/:title

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
  - scope:
      path: ""
      type: location
    values:
      layout: location

navigation:
  - title: Programm
    relative_url: /program/
    show_on_start: true
  - title: Vorträge
    relative_url: /talks/
  - title: SprecherInnen
    relative_url: /speakers/
  - title: Ort
    relative_url: /location/
    show_on_start: Anreise
  - title: Über uns
    relative_url: /about/
  - title: Kontakt
    relative_url: /contact/

category_colors:
  - rgb(231, 232, 234) # grey (default)
  - rgb(204, 229, 255) # blue
  - rgb(212, 237, 218) # green
  - rgb(248, 215, 218) # red
  - rgb(255, 243, 205) # yellow
  - rgb(209, 236, 241) # turquoise

time_steps: 15 # in minutes

# Exclude from processing..
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
