title: Congress 2018
description: >-
  A short description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  location:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talks
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
  - scope:
      path: ""
      type: location
    values:
      layout: location

navigation:
  - navbar_name: Program
    main_name: Program
    relative_url: /program/
  - navbar_name: Talks
    relative_url: /talks/
  - navbar_name: Speakers
    relative_url: /speakers/
  - navbar_name: Location
    main_name: How to get there
    relative_url: /location/
  - navbar_name: About
    relative_url: /about/
  - main_name: Tickets
    absolute_url: 'https://github.com'

main_categories:
  - name: Cat A
    color: primary
  - name: Cat B
    color: success

time_steps: 15 # in minutes

hide_links:
  location: false
  speakers:
    - The Anonymous
  talks:
    - Talk 2

# Exclude from processing..
exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
